// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj4IbWqLOOWp8lAUio9VM1oax-Uf9PrGA',
    appId: '1:760631040465:android:29a724a97128d339f2e8f0',
    messagingSenderId: '760631040465',
    projectId: 'movie-time-29763',
    storageBucket: 'movie-time-29763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Zdw9mJ-3oCU0BhNZ5-o_wEZZ64Iyzt4',
    appId: '1:760631040465:ios:f32e793dd0decb29f2e8f0',
    messagingSenderId: '760631040465',
    projectId: 'movie-time-29763',
    storageBucket: 'movie-time-29763.appspot.com',
    androidClientId: '760631040465-bt2gnvdteefnqknebka62ljg4l1i4h23.apps.googleusercontent.com',
    iosClientId: '760631040465-oo7setvbd836gj3p7pbkabmdtg5in8tu.apps.googleusercontent.com',
    iosBundleId: 'id.co.ridhaaf.movieTime',
  );
}
